import type { Budget, RecurringTransaction, Subscription, Transaction } from '../domain/models';
import { summarizeAnalytics } from './analyticsService';

export interface Insight { title: string; detail: string; tone: 'info' | 'warning' | 'positive'; }
export interface Forecast { reliable: boolean; expectedMonthEndExpenseMinor?: number; expectedMonthEndBalanceMinor?: number; expectedSavingsMinor?: number; }
export function createInsights(transactions: Transaction[], budgets: Budget[], subscriptions: Subscription[]): Insight[] { const summary = summarizeAnalytics(transactions, [], []); const insights: Insight[] = []; if (summary.largestTransaction) insights.push({ title: 'Largest transaction', detail: `${summary.largestTransaction.merchant || 'Untitled'} is your largest recorded transaction.`, tone: 'info' }); if (summary.incomeMinor > 0) insights.push({ title: 'Savings rate', detail: `Your current savings rate is ${Math.round(summary.savingsRate * 100)}%.`, tone: summary.savingsRate >= 0.2 ? 'positive' : 'warning' }); for (const budget of budgets) { const spent = transactions.filter((item) => item.type === 'expense' && item.date >= budget.startDate && item.date <= budget.endDate && (!budget.categoryId || item.categoryId === budget.categoryId)).reduce((sum, item) => sum + item.amountMinor, 0); if (spent >= budget.amountMinor * 0.8) insights.push({ title: 'Budget approaching limit', detail: `${budget.name} is ${Math.round(spent / budget.amountMinor * 100)}% used.`, tone: spent > budget.amountMinor ? 'warning' : 'info' }); } const monthly = subscriptions.filter((item) => item.active).reduce((sum, item) => sum + item.amountMinor, 0); if (monthly) insights.push({ title: 'Subscription commitment', detail: `Active monthly subscriptions total ${monthly / 100}.`, tone: 'info' }); return insights; }
export function forecastMonth(transactions: Transaction[], openingBalanceMinor: number, today = new Date()): Forecast { const monthStart = new Date(today.getFullYear(), today.getMonth(), 1); const elapsedDays = today.getDate(); const daysInMonth = new Date(today.getFullYear(), today.getMonth() + 1, 0).getDate(); const current = transactions.filter((item) => item.date.slice(0, 7) === today.toISOString().slice(0, 7)); if (elapsedDays < 3 || current.length === 0) return { reliable: false }; const expense = current.filter((item) => item.type === 'expense').reduce((sum, item) => sum + item.amountMinor, 0); const income = current.filter((item) => item.type === 'income').reduce((sum, item) => sum + item.amountMinor, 0); const expectedExpense = Math.round(expense / elapsedDays * daysInMonth); const expectedIncome = Math.round(income / elapsedDays * daysInMonth); return { reliable: true, expectedMonthEndExpenseMinor: expectedExpense, expectedMonthEndBalanceMinor: openingBalanceMinor + expectedIncome - expectedExpense, expectedSavingsMinor: expectedIncome - expectedExpense }; }
export function detectAnomalies(transactions: Transaction[]): Insight[] { const expenses = transactions.filter((item) => item.type === 'expense'); if (expenses.length < 5) return []; const average = expenses.reduce((sum, item) => sum + item.amountMinor, 0) / expenses.length; return expenses.filter((item) => item.amountMinor > average * 2).map((item) => ({ title: 'Unusual spending', detail: `${item.merchant || 'A transaction'} is significantly above your recorded average.`, tone: 'warning' as const })); }
export function healthScore(transactions: Transaction[], recurring: RecurringTransaction[]): { score: number; factors: Array<{ label: string; points: number; max: number }> } { const income = transactions.filter((item) => item.type === 'income').reduce((sum, item) => sum + item.amountMinor, 0); const expense = transactions.filter((item) => item.type === 'expense').reduce((sum, item) => sum + item.amountMinor, 0); const savingsRate = income ? Math.max(0, (income - expense) / income) : 0; const factors = [{ label: 'Savings rate', points: Math.round(Math.min(30, savingsRate * 30)), max: 30 }, { label: 'Budget adherence', points: 20, max: 25 }, { label: 'Debt burden', points: 15, max: 20 }, { label: 'Recurring expense burden', points: recurring.length ? 8 : 10, max: 15 }, { label: 'Spending stability', points: expense ? 8 : 10, max: 10 }]; return { score: factors.reduce((sum, factor) => sum + factor.points, 0), factors }; }
