import { Pencil, Plus, Archive, Trash2, Wallet } from 'lucide-react';
import { formatMoney, fromMinorUnits, toMinorUnits } from '../domain/money';
import type { Account, AccountType, CurrencyCode, Transaction } from '../domain/models';
import { accountService, type AccountInput } from '../services/accountService';
import { accountBalance } from '../domain/calculations';
import { useState } from 'react';

const accountTypes: AccountType[] = ['bank', 'cash', 'credit-card', 'wallet', 'investment', 'other'];
const currencies: CurrencyCode[] = ['INR', 'USD', 'EUR', 'GBP', 'AED', 'SGD', 'AUD', 'CAD', 'JPY', 'OTHER'];

export function AccountsPage({ accounts, transactions, onChanged }: { accounts: Account[]; transactions: Transaction[]; onChanged: () => Promise<void> }) {
  const [editing, setEditing] = useState<Account | null>(null);
  const [showForm, setShowForm] = useState(false);
  const [message, setMessage] = useState('');
  async function deactivate(account: Account) { if (!window.confirm(`Archive ${account.name}? Its history will remain available.`)) return; await accountService.deactivate(account.id); await onChanged(); }
  async function remove(account: Account) { if (!window.confirm(`Permanently delete ${account.name}?`)) return; try { await accountService.remove(account.id); await onChanged(); } catch (error) { setMessage(error instanceof Error ? error.message : 'Account could not be deleted'); } }
  return <div className="page-stack"><div className="page-heading"><div><p className="eyebrow">Money locations</p><h2>Accounts</h2><p className="muted">Balances are calculated from your ledger.</p></div><button className="primary-button" onClick={() => { setEditing(null); setShowForm(true); }}><Plus size={18} /> Add account</button></div>{message && <p className="form-error">{message}</p>}<div className="management-list">{accounts.map((account) => <div className="management-row" key={account.id}><span className="management-icon"><Wallet size={18} /></span><div className="management-main"><strong>{account.name}</strong><small>{account.type.replace('-', ' ')} · {account.currency}{account.active ? '' : ' · archived'}</small></div><strong>{formatMoney(accountBalance(account, transactions), account.currency)}</strong><div className="row-actions"><button className="icon-button small" aria-label={`Edit ${account.name}`} onClick={() => { setEditing(account); setShowForm(true); }}><Pencil size={15} /></button>{account.active && <button className="icon-button small" aria-label={`Archive ${account.name}`} onClick={() => void deactivate(account)}><Archive size={15} /></button>}<button className="icon-button small danger" aria-label={`Delete ${account.name}`} onClick={() => void remove(account)}><Trash2 size={15} /></button></div></div>)}</div>{showForm && <AccountForm account={editing} onClose={() => setShowForm(false)} onSaved={async () => { setShowForm(false); await onChanged(); }} />}</div>;
}

function AccountForm({ account, onClose, onSaved }: { account: Account | null; onClose: () => void; onSaved: () => Promise<void> }) {
  const [name, setName] = useState(account?.name ?? ''); const [type, setType] = useState<AccountType>(account?.type ?? 'bank'); const [currency, setCurrency] = useState<CurrencyCode>(account?.currency ?? 'INR'); const [opening, setOpening] = useState(account ? String(fromMinorUnits(account.openingBalanceMinor)) : ''); const [limit, setLimit] = useState(account?.creditLimitMinor === undefined ? '' : String(fromMinorUnits(account.creditLimitMinor))); const [error, setError] = useState('');
  async function submit(event: React.FormEvent) { event.preventDefault(); try { const input: AccountInput = { name, type, currency, openingBalanceMinor: Math.round(Number(opening || 0) * 100), creditLimitMinor: type === 'credit-card' && limit ? toMinorUnits(Number(limit)) : undefined }; if (account) await accountService.update(account.id, input); else await accountService.create(input); await onSaved(); } catch (submissionError) { setError(submissionError instanceof Error ? submissionError.message : 'Unable to save account'); } }
  return <div className="modal-backdrop"><form className="modal" onSubmit={(event) => void submit(event)}><div className="modal-header"><div><p className="eyebrow">Account setup</p><h2>{account ? 'Edit account' : 'Add account'}</h2></div><button type="button" className="icon-button" onClick={onClose}>×</button></div><label>Name<input required value={name} onChange={(event) => setName(event.target.value)} /></label><div className="form-row"><label>Type<select value={type} onChange={(event) => setType(event.target.value as AccountType)}>{accountTypes.map((item) => <option key={item} value={item}>{item.replace('-', ' ')}</option>)}</select></label><label>Currency<select value={currency} onChange={(event) => setCurrency(event.target.value as CurrencyCode)}>{currencies.map((item) => <option key={item} value={item}>{item}</option>)}</select></label></div><label>Opening balance<input type="number" step="0.01" inputMode="decimal" value={opening} onChange={(event) => setOpening(event.target.value)} /></label>{type === 'credit-card' && <label>Credit limit<input type="number" min="0" step="0.01" inputMode="decimal" value={limit} onChange={(event) => setLimit(event.target.value)} /></label>}{error && <p className="form-error">{error}</p>}<button className="primary-button full-width" type="submit">Save account</button></form></div>;
}
