import { Archive, Pencil, Plus, Tag, Trash2 } from 'lucide-react';
import { useState } from 'react';
import type { Category, Transaction } from '../domain/models';
import { categoryService, type CategoryInput } from '../services/categoryService';

export function CategoriesPage({ categories, transactions, onChanged }: { categories: Category[]; transactions: Transaction[]; onChanged: () => Promise<void> }) {
  const [editing, setEditing] = useState<Category | null>(null); const [showForm, setShowForm] = useState(false); const [message, setMessage] = useState('');
  async function deactivate(category: Category) { if (!window.confirm(`Archive ${category.name}? Existing transactions will remain unchanged.`)) return; await categoryService.deactivate(category.id); await onChanged(); }
  async function remove(category: Category) { if (!window.confirm(`Permanently delete ${category.name}?`)) return; try { await categoryService.remove(category.id); await onChanged(); } catch (error) { setMessage(error instanceof Error ? error.message : 'Category could not be deleted'); } }
  const parents = categories.filter((category) => !category.parentId);
  return <div className="page-stack"><div className="page-heading"><div><p className="eyebrow">Spending labels</p><h2>Categories</h2><p className="muted">Organize expenses now, ready for budgets later.</p></div><button className="primary-button" onClick={() => { setEditing(null); setShowForm(true); }}><Plus size={18} /> Add category</button></div>{message && <p className="form-error">{message}</p>}<div className="management-list">{parents.map((parent) => <div key={parent.id}><CategoryRow category={parent} transactions={transactions} onEdit={() => { setEditing(parent); setShowForm(true); }} onArchive={() => void deactivate(parent)} onDelete={() => void remove(parent)} />{categories.filter((category) => category.parentId === parent.id).map((child) => <CategoryRow key={child.id} category={child} transactions={transactions} nested onEdit={() => { setEditing(child); setShowForm(true); }} onArchive={() => void deactivate(child)} onDelete={() => void remove(child)} />)}</div>)}</div>{showForm && <CategoryForm category={editing} categories={categories} onClose={() => setShowForm(false)} onSaved={async () => { setShowForm(false); await onChanged(); }} />}</div>;
}
function CategoryRow({ category, transactions, nested, onEdit, onArchive, onDelete }: { category: Category; transactions: Transaction[]; nested?: boolean; onEdit: () => void; onArchive: () => void; onDelete: () => void }) { const count = transactions.filter((item) => item.categoryId === category.id).length; return <div className={nested ? 'management-row nested' : 'management-row'}><span className="management-icon" style={{ background: category.color, color: '#fff' }}><Tag size={17} /></span><div className="management-main"><strong>{category.name}</strong><small>{category.icon} · {count} transaction{count === 1 ? '' : 's'}{category.active ? '' : ' · archived'}</small></div><div className="row-actions"><button className="icon-button small" aria-label={`Edit ${category.name}`} onClick={onEdit}><Pencil size={15} /></button>{category.active && <button className="icon-button small" aria-label={`Archive ${category.name}`} onClick={onArchive}><Archive size={15} /></button>}<button className="icon-button small danger" aria-label={`Delete ${category.name}`} onClick={onDelete}><Trash2 size={15} /></button></div></div>; }
function CategoryForm({ category, categories, onClose, onSaved }: { category: Category | null; categories: Category[]; onClose: () => void; onSaved: () => Promise<void> }) { const [name, setName] = useState(category?.name ?? ''); const [icon, setIcon] = useState(category?.icon ?? 'tag'); const [color, setColor] = useState(category?.color ?? '#2a9d8f'); const [parentId, setParentId] = useState(category?.parentId ?? ''); const [error, setError] = useState(''); async function submit(event: React.FormEvent) { event.preventDefault(); try { const input: CategoryInput = { name, icon, color, parentId: parentId || undefined }; if (category) await categoryService.update(category.id, input); else await categoryService.create(input); await onSaved(); } catch (submissionError) { setError(submissionError instanceof Error ? submissionError.message : 'Unable to save category'); } } return <div className="modal-backdrop"><form className="modal" onSubmit={(event) => void submit(event)}><div className="modal-header"><div><p className="eyebrow">Category setup</p><h2>{category ? 'Edit category' : 'Add category'}</h2></div><button type="button" className="icon-button" onClick={onClose}>×</button></div><label>Name<input required value={name} onChange={(event) => setName(event.target.value)} /></label><div className="form-row"><label>Icon<input value={icon} onChange={(event) => setIcon(event.target.value)} /></label><label>Color<input type="color" value={color} onChange={(event) => setColor(event.target.value)} /></label></div><label>Parent category<select value={parentId} onChange={(event) => setParentId(event.target.value)}><option value="">None</option>{categories.filter((item) => !item.parentId && item.id !== category?.id).map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label>{error && <p className="form-error">{error}</p>}<button className="primary-button full-width" type="submit">Save category</button></form></div>; }
