import { useEffect, useState } from 'react';
import { CalendarDays, Download, Pause, Play, Plus, Search, Trash2, Upload } from 'lucide-react';
import { formatMoney, toMinorUnits } from '../domain/money';
import type { Account, Budget, Category, NewTransaction, RecurrenceFrequency, RecurringTransaction, Subscription, Transaction } from '../domain/models';
import { budgetService, type BudgetInput } from '../services/budgetService';
import { recurringService, type RecurringInput } from '../services/recurringService';
import { subscriptionService } from '../services/subscriptionService';
import { summarizeAnalytics } from '../services/analyticsService';
import { exportTransactionsCsv, normalizeCsvRows, parseCsv } from '../services/csvService';
import { transactionService } from '../services/transactionService';
import { createInsights, detectAnomalies, forecastMonth, healthScore } from '../services/insightService';
import { filterTransactions, sortTransactions, type TransactionFilter, type TransactionSort } from '../services/filterService';
import { TransactionSearchPage } from './TransactionSearchPage';

export type FeatureView = 'budgets' | 'recurring' | 'subscriptions' | 'calendar' | 'analytics' | 'search';

export function FeatureHub({ view, accounts, categories, transactions, onChanged }: { view: FeatureView; accounts: Account[]; categories: Category[]; transactions: Transaction[]; onChanged: () => Promise<void> }) {
  if (view === 'budgets') return <Budgets accounts={accounts} categories={categories} transactions={transactions} onChanged={onChanged} />;
  if (view === 'recurring') return <Recurring accounts={accounts} categories={categories} onChanged={onChanged} />;
  if (view === 'subscriptions') return <Subscriptions accounts={accounts} onChanged={onChanged} />;
  if (view === 'calendar') return <Calendar transactions={transactions} />;
  if (view === 'analytics') return <Analytics accounts={accounts} categories={categories} transactions={transactions} />;
  return <TransactionSearchPage accounts={accounts} categories={categories} transactions={transactions} />;
}

function Header({ eyebrow, title, description, action }: { eyebrow: string; title: string; description: string; action?: React.ReactNode }) { return <div className="page-heading"><div><p className="eyebrow">{eyebrow}</p><h2>{title}</h2><p className="muted">{description}</p></div>{action}</div>; }
function Budgets({ accounts, categories, transactions, onChanged }: { accounts: Account[]; categories: Category[]; transactions: Transaction[]; onChanged: () => Promise<void> }) { const [budgets, setBudgets] = useState<Budget[]>([]); const [show, setShow] = useState(false); useEffect(() => { void budgetService.list().then(setBudgets); }, []); const spent = (budget: Budget) => transactions.filter((item) => item.type === 'expense' && item.date >= budget.startDate && item.date <= budget.endDate && (!budget.categoryId || item.categoryId === budget.categoryId)).reduce((sum, item) => sum + item.amountMinor, 0); async function reload() { setBudgets(await budgetService.list()); await onChanged(); } return <div className="page-stack"><Header eyebrow="Guardrails" title="Budgets" description="Track spending against transparent date and category limits." action={<button className="primary-button" onClick={() => setShow(true)}><Plus size={18} /> Add budget</button>} />{show && <BudgetForm accounts={accounts} categories={categories} onClose={() => setShow(false)} onSaved={async () => { setShow(false); await reload(); }} />}{budgets.length === 0 ? <EmptyFeature text="No budgets yet. Create a monthly category guardrail." /> : budgets.map((budget) => { const amountSpent = spent(budget); const percent = Math.round(amountSpent / budget.amountMinor * 100); return <div className="feature-card" key={budget.id}><div className="feature-card-heading"><div><strong>{budget.name}</strong><small>{budget.categoryId ? categories.find((category) => category.id === budget.categoryId)?.name : 'All categories'} · {budget.startDate} to {budget.endDate}</small></div><button className="icon-button small danger" onClick={() => void budgetService.remove(budget.id).then(reload)}><Trash2 size={15} /></button></div><div className="budget-amounts"><span>{formatMoney(amountSpent, budget.currency)} spent</span><strong>{formatMoney(budget.amountMinor, budget.currency)} limit</strong></div><div className="progress-track"><div className={percent >= 100 ? 'progress-value over' : 'progress-value'} style={{ width: `${Math.min(100, percent)}%` }} /></div><small className="muted">{percent}% used · {amountSpent > budget.amountMinor ? `Over budget by ${formatMoney(amountSpent - budget.amountMinor, budget.currency)}` : `${formatMoney(budget.amountMinor - amountSpent, budget.currency)} remaining`}</small></div>; })}</div>; }
function BudgetForm({ categories, onClose, onSaved }: { accounts: Account[]; categories: Category[]; onClose: () => void; onSaved: () => Promise<void> }) { const [name, setName] = useState('Monthly budget'); const [amount, setAmount] = useState(''); const [categoryId, setCategoryId] = useState(''); const [startDate, setStartDate] = useState(new Date().toISOString().slice(0, 8) + '01'); const [endDate, setEndDate] = useState(new Date().toISOString().slice(0, 7) + '-30'); const [error, setError] = useState(''); async function submit(event: React.FormEvent) { event.preventDefault(); try { const input: BudgetInput = { name, amountMinor: toMinorUnits(Number(amount)), currency: 'INR', categoryId: categoryId || undefined, startDate, endDate, period: 'monthly', rollover: false }; await budgetService.create(input); await onSaved(); } catch (submissionError) { setError(submissionError instanceof Error ? submissionError.message : 'Unable to save budget'); } } return <Modal title="Add budget" onClose={onClose} onSubmit={submit} error={error}><label>Name<input required value={name} onChange={(event) => setName(event.target.value)} /></label><label>Amount<input required type="number" min="0.01" step="0.01" value={amount} onChange={(event) => setAmount(event.target.value)} /></label><label>Category<select value={categoryId} onChange={(event) => setCategoryId(event.target.value)}><option value="">All categories</option>{categories.map((category) => <option key={category.id} value={category.id}>{category.name}</option>)}</select></label><div className="form-row"><label>Start<input type="date" value={startDate} onChange={(event) => setStartDate(event.target.value)} /></label><label>End<input type="date" value={endDate} onChange={(event) => setEndDate(event.target.value)} /></label></div></Modal>; }
function Recurring({ accounts, categories, onChanged }: { accounts: Account[]; categories: Category[]; onChanged: () => Promise<void> }) { const [items, setItems] = useState<RecurringTransaction[]>([]); const [show, setShow] = useState(false); useEffect(() => { void recurringService.list().then(setItems); }, []); async function reload() { setItems(await recurringService.list()); await onChanged(); } return <div className="page-stack"><Header eyebrow="Scheduled" title="Recurring transactions" description="Definitions stay separate from actual ledger entries." action={<button className="primary-button" onClick={() => setShow(true)}><Plus size={18} /> Add recurring</button>} />{show && <RecurringForm accounts={accounts} categories={categories} onClose={() => setShow(false)} onSaved={async () => { setShow(false); await reload(); }} />}{items.length === 0 ? <EmptyFeature text="No recurring definitions yet." /> : items.map((item) => <div className="feature-card" key={item.id}><div className="feature-card-heading"><div><strong>{item.name}</strong><small>{item.frequency} · next {item.nextOccurrence} · {formatMoney(item.amountMinor)}</small></div><button className="icon-button small" onClick={() => void recurringService.setActive(item.id, !item.active).then(reload)}>{item.active ? <Pause size={15} /> : <Play size={15} />}</button></div></div>)}</div>; }
function RecurringForm({ accounts, categories, onClose, onSaved }: { accounts: Account[]; categories: Category[]; onClose: () => void; onSaved: () => Promise<void> }) { const [name, setName] = useState('Salary'); const [amount, setAmount] = useState(''); const [frequency, setFrequency] = useState<RecurrenceFrequency>('monthly'); const [accountId, setAccountId] = useState(accounts[0]?.id ?? ''); const [categoryId, setCategoryId] = useState(categories[0]?.id ?? ''); const [nextOccurrence, setNextOccurrence] = useState(new Date().toISOString().slice(0, 10)); const [error, setError] = useState(''); async function submit(event: React.FormEvent) { event.preventDefault(); try { const input: RecurringInput = { name, amountMinor: toMinorUnits(Number(amount)), type: name.toLowerCase().includes('salary') ? 'income' : 'expense', accountId, categoryId, currency: 'INR', frequency, interval: 1, startDate: nextOccurrence, nextOccurrence, notes: '' }; await recurringService.create(input); await onSaved(); } catch (submissionError) { setError(submissionError instanceof Error ? submissionError.message : 'Unable to save recurring transaction'); } } return <Modal title="Add recurring transaction" onClose={onClose} onSubmit={submit} error={error}><label>Name<input required value={name} onChange={(event) => setName(event.target.value)} /></label><label>Amount<input required type="number" min="0.01" step="0.01" value={amount} onChange={(event) => setAmount(event.target.value)} /></label><div className="form-row"><label>Frequency<select value={frequency} onChange={(event) => setFrequency(event.target.value as RecurrenceFrequency)}>{['daily', 'weekly', 'monthly', 'yearly', 'custom'].map((value) => <option key={value}>{value}</option>)}</select></label><label>Account<select value={accountId} onChange={(event) => setAccountId(event.target.value)}>{accounts.map((account) => <option key={account.id} value={account.id}>{account.name}</option>)}</select></label></div><label>Category<select value={categoryId} onChange={(event) => setCategoryId(event.target.value)}>{categories.map((category) => <option key={category.id} value={category.id}>{category.name}</option>)}</select></label><label>Next occurrence<input type="date" value={nextOccurrence} onChange={(event) => setNextOccurrence(event.target.value)} /></label></Modal>; }
function Subscriptions({ accounts, onChanged }: { accounts: Account[]; onChanged: () => Promise<void> }) { const [items, setItems] = useState<Subscription[]>([]); const [show, setShow] = useState(false); useEffect(() => { void subscriptionService.list().then(setItems); }, []); async function reload() { setItems(await subscriptionService.list()); await onChanged(); } return <div className="page-stack"><Header eyebrow="Commitments" title="Subscriptions" description={`Estimated monthly cost: ${formatMoney(subscriptionService.monthlyCost(items))}`} action={<button className="primary-button" onClick={() => setShow(true)}><Plus size={18} /> Add subscription</button>} />{show && <SubscriptionForm accounts={accounts} onClose={() => setShow(false)} onSaved={async () => { setShow(false); await reload(); }} />}{items.length === 0 ? <EmptyFeature text="No subscriptions. Definitions never create transactions automatically." /> : items.map((item) => <div className="feature-card" key={item.id}><div className="feature-card-heading"><div><strong>{item.name}</strong><small>{formatMoney(item.amountMinor)} · {item.billingFrequency} · day {item.billingDay}</small></div><button className="icon-button small danger" onClick={() => void subscriptionService.remove(item.id).then(reload)}><Trash2 size={15} /></button></div></div>)}</div>; }
function SubscriptionForm({ accounts = [], onClose, onSaved }: { accounts?: Account[]; onClose: () => void; onSaved: () => Promise<void> }) { const [name, setName] = useState('Subscription'); const [amount, setAmount] = useState(''); const [accountId, setAccountId] = useState(accounts[0]?.id ?? ''); const [error, setError] = useState(''); async function submit(event: React.FormEvent) { event.preventDefault(); try { if (!accountId) throw new Error('Choose an account'); await subscriptionService.create({ name, amountMinor: toMinorUnits(Number(amount)), currency: 'INR', billingFrequency: 'monthly', billingDay: 1, accountId, notes: '' }); await onSaved(); } catch (submissionError) { setError(submissionError instanceof Error ? submissionError.message : 'Unable to save subscription'); } } return <Modal title="Add subscription" onClose={onClose} onSubmit={submit} error={error}><label>Name<input required value={name} onChange={(event) => setName(event.target.value)} /></label><label>Monthly amount<input required type="number" min="0.01" step="0.01" value={amount} onChange={(event) => setAmount(event.target.value)} /></label><label>Account<select required value={accountId} onChange={(event) => setAccountId(event.target.value)}>{accounts.map((account) => <option key={account.id} value={account.id}>{account.name}</option>)}</select></label></Modal>; }
function Calendar({ transactions }: { transactions: Transaction[] }) { const [month, setMonth] = useState(new Date().toISOString().slice(0, 7)); const days = new Date(Number(month.slice(0, 4)), Number(month.slice(5, 7)), 0).getDate(); const dayRows = Array.from({ length: days }, (_, index) => { const date = `${month}-${String(index + 1).padStart(2, '0')}`; const items = transactions.filter((item) => item.date === date); return { date, items, income: items.filter((item) => item.type === 'income').reduce((sum, item) => sum + item.amountMinor, 0), expense: items.filter((item) => item.type === 'expense').reduce((sum, item) => sum + item.amountMinor, 0) }; }); return <div className="page-stack"><Header eyebrow="Timeline" title="Calendar" description="Daily income, expenses, and net movement." action={<input type="month" value={month} onChange={(event) => setMonth(event.target.value)} />} /><div className="calendar-grid">{dayRows.map((day) => <div className={day.items.length ? 'calendar-day has-items' : 'calendar-day'} key={day.date}><strong>{day.date.slice(-2)}</strong><small>{day.income ? `+${formatMoney(day.income)}` : ''}</small><small>{day.expense ? `-${formatMoney(day.expense)}` : ''}</small></div>)}</div></div>; }
function Analytics({ accounts, categories, transactions }: { accounts: Account[]; categories: Category[]; transactions: Transaction[] }) { const summary = summarizeAnalytics(transactions, accounts, categories); return <div className="page-stack"><Header eyebrow="Patterns" title="Analytics" description="Transparent calculations from your local ledger." /><div className="stat-grid"><div className="stat-card"><div><p>Income</p><strong>{formatMoney(summary.incomeMinor)}</strong></div></div><div className="stat-card"><div><p>Expenses</p><strong>{formatMoney(summary.expenseMinor)}</strong></div></div><div className="stat-card"><div><p>Savings rate</p><strong>{Math.round(summary.savingsRate * 100)}%</strong></div></div></div><div className="feature-card"><h3>Top categories</h3>{summary.byCategory.length ? summary.byCategory.map((item) => <div className="feature-line" key={item.name}><span>{item.name}</span><strong>{formatMoney(item.amountMinor)}</strong></div>) : <EmptyFeature text="Add transactions to see patterns." />}</div><div className="feature-card"><h3>Largest and average</h3><p className="muted">Average daily spending: {formatMoney(summary.averageDailyExpenseMinor)}</p><p className="muted">Largest transaction: {summary.largestTransaction ? `${summary.largestTransaction.merchant} · ${formatMoney(summary.largestTransaction.amountMinor)}` : 'None yet'}</p></div></div>; }
function SearchTransactions({ accounts, categories, transactions }: { accounts: Account[]; categories: Category[]; transactions: Transaction[] }) { const [query, setQuery] = useState(''); const [importRows, setImportRows] = useState<Array<{ transaction: NewTransaction; duplicate: boolean }>>([]); const results = transactions.filter((item) => { const account = accounts.find((value) => value.id === item.accountId)?.name ?? ''; const category = categories.find((value) => value.id === item.categoryId)?.name ?? ''; return `${item.merchant} ${item.notes} ${item.tags.join(' ')} ${account} ${category} ${item.reference ?? ''}`.toLowerCase().includes(query.toLowerCase()); }); async function importConfirmed() { for (const row of importRows.filter((item) => !item.duplicate)) await transactionService.create(row.transaction); setImportRows([]); } return <div className="page-stack"><Header eyebrow="Find" title="Search & import" description="Search your ledger, export results, or preview a CSV before importing." /><div className="search-box"><Search size={18} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search your ledger" /></div><div className="section-card transaction-table">{query && results.length === 0 ? <EmptyFeature text="No matching transactions." /> : results.map((item) => <div className="feature-line" key={item.id}><span>{item.merchant || item.type}<small>{item.date} · {item.tags.join(', ')}</small></span><strong>{formatMoney(item.amountMinor, item.currency)}</strong></div>)}</div><div className="settings-actions"><button className="secondary-button" onClick={() => { const content = exportTransactionsCsv(results, accounts, categories); const link = document.createElement('a'); link.href = URL.createObjectURL(new Blob([content], { type: 'text/csv' })); link.download = 'v-finance-transactions.csv'; link.click(); }}><Download size={17} /> Export current results</button><label className="secondary-button"><Upload size={17} /> Preview CSV<input hidden type="file" accept="text/csv,.csv" onChange={async (event) => { const file = event.target.files?.[0]; if (file) setImportRows(normalizeCsvRows(parseCsv(await file.text()), accounts, categories, transactions)); }} /></label></div>{importRows.length > 0 && <div className="feature-card"><h3>Import preview</h3><p className="muted">{importRows.length} rows detected. Duplicates are excluded until you review the preview.</p>{importRows.slice(0, 8).map((row, index) => <div className="feature-line" key={`${row.transaction.date}-${index}`}><span>{row.transaction.merchant}<small>{row.transaction.date} · {row.duplicate ? 'Possible duplicate' : 'Ready to import'}</small></span><strong>{formatMoney(row.transaction.amountMinor, row.transaction.currency)}</strong></div>)}<button className="primary-button" onClick={() => void importConfirmed()}>Confirm import</button></div>}</div>; }
function Modal({ title, onClose, onSubmit, error, children }: { title: string; onClose: () => void; onSubmit: (event: React.FormEvent) => void; error: string; children: React.ReactNode }) { return <div className="modal-backdrop"><form className="modal" role="dialog" aria-modal="true" aria-labelledby="feature-modal-title" onKeyDown={(event) => { if (event.key === 'Escape') { event.preventDefault(); onClose(); } }} onSubmit={onSubmit}><div className="modal-header"><h2 id="feature-modal-title">{title}</h2><button type="button" className="icon-button" onClick={onClose} aria-label="Close dialog">×</button></div>{children}{error && <p className="form-error" role="alert">{error}</p>}<button className="primary-button full-width" type="submit">Save</button></form></div>; }
function EmptyFeature({ text }: { text: string }) { return <div className="empty-inline"><CalendarDays size={22} /><p>{text}</p></div>; }



