import { useEffect, useState } from 'react';
import { Pencil, Plus, Trash2 } from 'lucide-react';
import { formatMoney, toMinorUnits } from '../domain/money';
import type { Investment, Loan, SavingsGoal, Trip, Transaction } from '../domain/models';
import { transactionService } from '../services/transactionService';
import { personalService } from '../services/personalService';

export type PersonalView = 'goals' | 'loans' | 'investments' | 'trips';
type Item = SavingsGoal | Loan | Investment | Trip;
const date = () => new Date().toISOString().slice(0, 10);

export function PersonalHub({ view, transactions = [] }: { view: PersonalView; transactions?: Transaction[] }) {
  const [items, setItems] = useState<Item[]>([]); const [itemsView, setItemsView] = useState<PersonalView | null>(null); const [show, setShow] = useState(false); const [editing, setEditing] = useState<Item | null>(null); const [error, setError] = useState('');
  async function load(forView: PersonalView = view) { const next = forView === 'goals' ? await personalService.goals() : forView === 'loans' ? await personalService.loans() : forView === 'investments' ? await personalService.investments() : await personalService.trips(); setItems(next); setItemsView(forView); }
  useEffect(() => { let current = true; setItemsView(null); void (async () => { try { const next = view === 'goals' ? await personalService.goals() : view === 'loans' ? await personalService.loans() : view === 'investments' ? await personalService.investments() : await personalService.trips(); if (current) { setItems(next); setItemsView(view); } } catch (e) { if (current) setError(e instanceof Error ? e.message : 'Unable to load records'); } })(); return () => { current = false; }; }, [view]);
  const title = view[0].toUpperCase() + view.slice(1);
  async function remove(item: Item) { if (!window.confirm(`Delete ${'name' in item ? item.name : 'item'}?`)) return; try { if (view === 'investments') await personalService.deleteInvestment(item.id); else if (view === 'goals') await personalService.deleteGoal(item.id); else if (view === 'loans') await personalService.deleteLoan(item.id); else await personalService.deleteTrip(item.id); await load(); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to delete'); } }
  return <div className="page-stack"><div className="page-heading"><div><p className="eyebrow">Planning</p><h2>{title}</h2><p className="muted">Editable local records with no account or paid service.</p></div><button className="primary-button" onClick={() => { setEditing(null); setShow(true); }}><Plus size={18} /> Add</button></div>{error && <p className="form-error" role="alert">{error}</p>}{show && <PersonalForm view={view} initial={editing} onClose={() => setShow(false)} onSaved={async () => { setShow(false); await load(); }} />}{itemsView !== view ? <div className="section-card" role="status">Loading {view}…</div> : items.length === 0 ? <div className="section-card"><div className="empty-page"><h2>No {view} yet</h2><p>Add your first {view.slice(0, -1)} to start tracking it locally.</p></div></div> : items.map((item) => <div className="feature-card" key={item.id}><div className="feature-card-heading"><div><strong>{'name' in item ? item.name : ''}</strong>{view === 'goals' && <small>{formatMoney((item as SavingsGoal).currentMinor)} of {formatMoney((item as SavingsGoal).targetMinor)}{(item as SavingsGoal).targetDate ? ` · target ${(item as SavingsGoal).targetDate}` : ''}</small>}{view === 'loans' && <small>EMI {formatMoney((item as Loan).emiMinor)} · {formatMoney((item as Loan).paidMinor)} paid · {Number((item as Loan).interestRate ?? 0).toFixed(2)}% interest</small>}{view === 'investments' && <small>{(item as Investment).type} · {formatMoney((item as Investment).investedMinor)} invested · {formatMoney((item as Investment).currentValueMinor)} current</small>}{view === 'trips' && <><small>{(item as Trip).destination} · {(item as Trip).startDate} to {(item as Trip).endDate}{(item as Trip).budgetMinor ? ` · budget ${formatMoney((item as Trip).budgetMinor!)}` : ''}</small><TripAssignment trip={item as Trip} transactions={transactions} /></>}</div><div className="row-actions"><button className="icon-button" onClick={() => { setEditing(item); setShow(true); }} aria-label={`Edit ${'name' in item ? item.name : view.slice(0, -1)}`}><Pencil size={15} /></button><button className="icon-button" onClick={() => void remove(item)} aria-label={`Delete ${'name' in item ? item.name : view.slice(0, -1)}`}><Trash2 size={15} /></button></div></div></div>)}</div>;
}

function PersonalForm({ view, initial, onClose, onSaved }: { view: PersonalView; initial: Item | null; onClose: () => void; onSaved: () => Promise<void> }) {
  const item = initial as any; const [name, setName] = useState(item?.name ?? ''); const [amount, setAmount] = useState(item ? String((item.targetMinor ?? item.principalMinor ?? item.investedMinor ?? item.budgetMinor ?? 0) / 100) : ''); const [error, setError] = useState('');
  const [destination, setDestination] = useState(item?.destination ?? ''); const [startDate, setStartDate] = useState(item?.startDate ?? date()); const [endDate, setEndDate] = useState(item?.endDate ?? date()); const [rate, setRate] = useState(String(item?.interestRate ?? 0)); const [tenure, setTenure] = useState(String(item?.tenureMonths ?? 12)); const [paid, setPaid] = useState(String((item?.paidMinor ?? 0) / 100)); const [type, setType] = useState(item?.type ?? 'other'); const [current, setCurrent] = useState(String((item?.currentValueMinor ?? item?.investedMinor ?? 0) / 100)); const [units, setUnits] = useState(String(item?.units ?? 1));
  async function submit(event: React.FormEvent) { event.preventDefault(); try { const amountMinor = toMinorUnits(Number(amount)); if (view === 'goals') { const payload = { name, targetMinor: amountMinor, currentMinor: initial ? item.currentMinor : 0, currency: 'INR' as const, targetDate: initial ? item.targetDate : undefined, notes: initial ? item.notes : '' }; if (initial) await personalService.updateGoal(initial.id, payload); else await personalService.addGoal(payload); }
    if (view === 'loans') { const principalMinor = amountMinor; const months = Math.max(1, Number(tenure)); const monthly = Number(rate) === 0 ? principalMinor / months : principalMinor * (Number(rate) / 1200) * (1 + Number(rate) / 1200) ** months / ((1 + Number(rate) / 1200) ** months - 1); const payload = { name, principalMinor, interestRate: Number(rate), tenureMonths: months, emiMinor: Math.round(monthly), startDate, paidMinor: toMinorUnits(Number(paid)) }; if (initial) await personalService.updateLoan(initial.id, payload); else await personalService.addLoan(payload); }
    if (view === 'investments') { const investedMinor = amountMinor; const payload = { name, type, units: Number(units), purchasePriceMinor: units ? Math.round(investedMinor / Number(units)) : investedMinor, investedMinor, currentValueMinor: toMinorUnits(Number(current)), currency: 'INR' as const, date: initial ? (initial as Investment).date : startDate }; if (initial) await personalService.updateInvestment(initial.id, payload); else await personalService.addInvestment(payload); }
    if (view === 'trips') { const payload = { name, destination: destination || 'Unspecified', startDate, endDate, notes: initial && 'notes' in initial ? initial.notes : '', budgetMinor: amount ? amountMinor : undefined }; if (initial) await personalService.updateTrip(initial.id, payload); else await personalService.addTrip(payload); }
    await onSaved(); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to save'); } }
  return <div className="modal-backdrop"><form className="modal" role="dialog" aria-modal="true" aria-labelledby="personal-form-title" onKeyDown={(e) => { if (e.key === 'Escape') { e.preventDefault(); onClose(); } }} onSubmit={(e) => void submit(e)}><div className="modal-header"><h2 id="personal-form-title">{initial ? 'Edit' : 'Add'} {view.slice(0, -1)}</h2><button type="button" className="icon-button" onClick={onClose} aria-label="Close dialog">×</button></div><label>Name<input autoFocus required value={name} onChange={(e) => setName(e.target.value)} /></label>{view === 'trips' && <><label>Destination<input value={destination} onChange={(e) => setDestination(e.target.value)} /></label><div className="form-row"><label>Start<input type="date" value={startDate} onChange={(e) => setStartDate(e.target.value)} /></label><label>End<input type="date" value={endDate} onChange={(e) => setEndDate(e.target.value)} /></label></div></>}{view !== 'trips' || initial ? <label>{view === 'goals' ? 'Target' : view === 'investments' ? 'Invested amount' : 'Principal'}<input required type="number" min="0.01" step="0.01" value={amount} onChange={(e) => setAmount(e.target.value)} /></label> : <label>Budget<input type="number" min="0" step="0.01" value={amount} onChange={(e) => setAmount(e.target.value)} /></label>}{view === 'loans' && <><div className="form-row"><label>Interest %<input type="number" min="0" step="0.01" value={rate} onChange={(e) => setRate(e.target.value)} /></label><label>Tenure months<input type="number" min="1" value={tenure} onChange={(e) => setTenure(e.target.value)} /></label></div><label>Paid so far<input type="number" min="0" step="0.01" value={paid} onChange={(e) => setPaid(e.target.value)} /></label><label>Start date<input type="date" value={startDate} onChange={(e) => setStartDate(e.target.value)} /></label></>}{view === 'investments' && <><div className="form-row"><label>Type<select value={type} onChange={(e) => setType(e.target.value)}>{['stocks','mutual-fund','sip','fd','gold','epf','ppf','other'].map((v) => <option key={v}>{v}</option>)}</select></label><label>Units<input type="number" min="0" step="0.0001" value={units} onChange={(e) => setUnits(e.target.value)} /></label></div><label>Current value<input type="number" min="0" step="0.01" value={current} onChange={(e) => setCurrent(e.target.value)} /></label><label>Date<input type="date" value={startDate} onChange={(e) => setStartDate(e.target.value)} /></label></>}{error && <p className="form-error" role="alert">{error}</p>}<button className="primary-button full-width" type="submit">Save</button></form></div>;
}

function TripAssignment({ trip, transactions }: { trip: Trip; transactions: Transaction[] }) { const [selected, setSelected] = useState(''); const assigned = transactions.filter((item) => item.tripId === trip.id); async function assign() { if (!selected) return; await transactionService.update(selected, { tripId: trip.id }); setSelected(''); } async function unassign(id: string) { await transactionService.update(id, { tripId: undefined }); } return <div className="trip-assignment"><div className="form-row"><select value={selected} onChange={(e) => setSelected(e.target.value)}><option value="">Assign transaction…</option>{transactions.filter((item) => !item.tripId).map((item) => <option key={item.id} value={item.id}>{item.date} · {item.merchant} · {formatMoney(item.amountMinor, item.currency)}</option>)}</select><button type="button" className="secondary-button" onClick={() => void assign()}>Assign</button></div>{assigned.length > 0 && <div className="trip-transactions">{assigned.map((item) => <div className="feature-line" key={item.id}><span>{item.date} · {item.merchant}<small>{item.type}</small></span><button type="button" className="text-button" onClick={() => void unassign(item.id)}>Remove</button></div>)}</div>}</div>; }
