import { useEffect, useState } from 'react';
import type { Account, Category, RecurringAudit, Transaction } from '../domain/models';
import { database } from '../db/database';
import { printableReport, reportSummary } from '../services/reportService';
import { formatMoney } from '../domain/money';
import { recurringService } from '../services/recurringService';

export function ReportsPage({ accounts, categories, transactions }: { accounts: Account[]; categories: Category[]; transactions: Transaction[] }) { const [kind,setKind]=useState('monthly'); const [from,setFrom]=useState(new Date(new Date().getFullYear(),new Date().getMonth(),1).toISOString().slice(0,10)); const [to,setTo]=useState(new Date().toISOString().slice(0,10)); const filtered=transactions.filter((item)=>item.date>=from&&item.date<=to); const summary=reportSummary(filtered,accounts,categories); function print(){const popup=window.open('','_blank','noopener,noreferrer');if(!popup)return;popup.document.write(printableReport(`V-Finance ${kind} report`,filtered,accounts,categories));popup.document.close();} return <div className="page-stack reports-page"><div className="page-heading"><div><p className="eyebrow">Documents</p><h2>Reports</h2><p className="muted">Local, print-ready financial reports. Use the browser print dialog to save PDF.</p></div><button className="primary-button" onClick={print}>Print / Save PDF</button></div><div className="filter-panel"><label>Report<select value={kind} onChange={(e)=>setKind(e.target.value)}>{['monthly','yearly','category','account','budget','net-worth','income-vs-expense'].map((v)=><option key={v}>{v}</option>)}</select></label><label>From<input type="date" value={from} onChange={(e)=>setFrom(e.target.value)}/></label><label>To<input type="date" value={to} onChange={(e)=>setTo(e.target.value)}/></label></div><div className="stat-grid"><div className="stat-card"><div><p>Income</p><strong>{formatMoney(summary.income)}</strong></div></div><div className="stat-card"><div><p>Expenses</p><strong>{formatMoney(summary.expense)}</strong></div></div><div className="stat-card"><div><p>Net</p><strong>{formatMoney(summary.net)}</strong></div></div></div><div className="feature-card"><h3>Category breakdown</h3>{summary.byCategory.length?summary.byCategory.map((item)=><div className="feature-line" key={item.name}><span>{item.name}</span><strong>{formatMoney(item.amountMinor)}</strong></div>):<p className="muted">No expenses in this period.</p>}</div><div className="section-card"><h3>{kind} detail</h3><p className="muted">{filtered.length} ledger entries · {from} to {to}</p>{filtered.map((item)=><div className="feature-line" key={item.id}><span>{item.date} · {item.merchant||item.type}<small>{item.type}</small></span><strong>{formatMoney(item.amountMinor,item.currency)}</strong></div>)}</div></div>; }

export function RecurringAuditPage() { const [items,setItems]=useState<RecurringAudit[]>([]); const [selected,setSelected]=useState<RecurringAudit|null>(null); const [message,setMessage]=useState(''); async function load(){setItems(await database.recurringAudit.orderBy('scheduledDate').reverse().toArray());} useEffect(()=>{void load();},[]); async function retry(item:RecurringAudit){const recurring=await database.recurring.get(item.recurringId);if(!recurring){setMessage('Recurring definition no longer exists.');return;} await recurringService.generateDue(item.scheduledDate);setMessage('Due occurrences checked.');await load();} return <div className="page-stack"><div className="page-heading"><div><p className="eyebrow">Scheduled history</p><h2>Recurring audit</h2><p className="muted">Inspect generated/failed occurrences and retry failed definitions safely.</p></div><button className="secondary-button" onClick={()=>void load()}>Refresh</button></div>{message&&<p className="muted">{message}</p>}<div className="section-card">{items.length===0?<p className="muted">No recurring occurrences have been generated.</p>:items.map((item)=><button className="feature-line audit-button" key={item.id} onClick={()=>setSelected(item)}><span>{item.scheduledDate}<small>{item.recurringId} · {item.generatedAt}</small></span><strong>{item.status}{item.error?` · ${item.error}`:''}</strong></button>)}</div>{selected&&<div className="modal-backdrop"><div className="modal"><div className="modal-header"><div><p className="eyebrow">Audit detail</p><h2>{selected.status}</h2></div><button className="icon-button" onClick={()=>setSelected(null)}>×</button></div><p className="muted">Recurring ID: {selected.recurringId}</p><p className="muted">Scheduled: {selected.scheduledDate}</p><p className="muted">Generated: {selected.generatedAt}</p>{selected.transactionId&&<p className="muted">Transaction: {selected.transactionId}</p>}{selected.error&&<p className="form-error">{selected.error}</p>}{selected.status==='failed'&&<button className="primary-button" onClick={()=>void retry(selected)}>Retry generation</button>}</div></div>}</div>; }
