import { useEffect, useState } from 'react';
import { Plus, Check } from 'lucide-react';
import type { Account, Category, Person, SplitShare, Transaction } from '../domain/models';
import { financialServices } from '../services/financialServices';
import { formatMoney, toMinorUnits } from '../domain/money';

export function SplitExpensesPage({ transactions }: { transactions: Transaction[]; accounts: Account[]; categories: Category[] }) {
  const [people, setPeople] = useState<Person[]>([]); const [splits, setSplits] = useState<SplitShare[]>([]); const [personName, setPersonName] = useState(''); const [selectedTransaction, setSelectedTransaction] = useState(transactions.find((item) => item.type === 'expense')?.id ?? ''); const [selectedPerson, setSelectedPerson] = useState(''); const [owed, setOwed] = useState(''); const [paid, setPaid] = useState(''); const [message, setMessage] = useState('');
  async function load() { const [p, s] = await Promise.all([financialServices.people(), Promise.all(transactions.filter((item) => item.type === 'expense').map((item) => financialServices.splitsFor(item.id)))]); setPeople(p); setSplits(s.flat()); if (!selectedPerson && p[0]) setSelectedPerson(p[0].id); }
  useEffect(() => { void load(); }, [transactions.length]);
  async function addPerson(e: React.FormEvent) { e.preventDefault(); try { const person = await financialServices.addPerson(personName); setPersonName(''); setSelectedPerson(person.id); await load(); } catch (e) { setMessage(e instanceof Error ? e.message : 'Unable to add person'); } }
  async function addShare(e: React.FormEvent) { e.preventDefault(); if (!selectedTransaction || !selectedPerson) return; try { await financialServices.addSplit({ transactionId: selectedTransaction, personId: selectedPerson, owedMinor: toMinorUnits(Number(owed)), paidMinor: toMinorUnits(Number(paid || 0)) }); setOwed(''); setPaid(''); setMessage('Split saved.'); await load(); } catch (e) { setMessage(e instanceof Error ? e.message : 'Unable to save split'); } }
  const balances = people.map((person) => { const rows = splits.filter((item) => item.personId === person.id); const balance = rows.reduce((sum, item) => sum + item.owedMinor - item.paidMinor, 0); return { person, balance }; });
  async function settle(id: string) { const row = splits.find((item) => item.id === id); if (!row) return; await financialServices.settleSplit(id); await load(); }
  return <div className="page-stack"><div className="page-heading"><div><p className="eyebrow">Shared spending</p><h2>Split expenses</h2><p className="muted">Track who owes you and mark shares settled without changing the original expense.</p></div></div><div className="content-grid"><form className="feature-card" onSubmit={(e) => void addPerson(e)}><h3>People</h3><div className="form-row"><input placeholder="Name" value={personName} onChange={(e) => setPersonName(e.target.value)} /><button className="primary-button" type="submit"><Plus size={15} /> Add</button></div>{balances.map(({ person, balance }) => <div className="feature-line" key={person.id}><span>{person.name}</span><strong>{formatMoney(balance)}</strong></div>)}</form><form className="feature-card" onSubmit={(e) => void addShare(e)}><h3>Add split share</h3><label>Expense<select value={selectedTransaction} onChange={(e) => setSelectedTransaction(e.target.value)}>{transactions.filter((item) => item.type === 'expense').map((item) => <option key={item.id} value={item.id}>{item.date} · {item.merchant} · {formatMoney(item.amountMinor, item.currency)}</option>)}</select></label><label>Person<select value={selectedPerson} onChange={(e) => setSelectedPerson(e.target.value)}>{people.map((p) => <option key={p.id} value={p.id}>{p.name}</option>)}</select></label><div className="form-row"><label>Owed<input required type="number" min="0" step="0.01" value={owed} onChange={(e) => setOwed(e.target.value)} /></label><label>Already paid<input type="number" min="0" step="0.01" value={paid} onChange={(e) => setPaid(e.target.value)} /></label></div><button className="primary-button" type="submit">Save share</button>{message && <p className="muted">{message}</p>}</form></div><div className="feature-card"><h3>Open shares</h3>{splits.filter((item) => !item.settledAt && item.owedMinor > item.paidMinor).length === 0 ? <p className="muted">No outstanding shares.</p> : splits.filter((item) => !item.settledAt && item.owedMinor > item.paidMinor).map((item) => <div className="feature-line" key={item.id}><span>{people.find((p) => p.id === item.personId)?.name ?? 'Unknown'}<small>{transactions.find((t) => t.id === item.transactionId)?.merchant ?? 'Expense'} · owes {formatMoney(item.owedMinor - item.paidMinor)}</small></span><button className="secondary-button" onClick={() => void settle(item.id)}><Check size={14} /> Settle</button></div>)}</div></div>;
}
